name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: npmExecuteLint
        uses: SAP/project-piper-action@master
        with:
          command: npmExecuteLint
      - name: mtaBuild
        uses: SAP/project-piper-action@master
        with:
#           command: mtaBuild
#       - name: cloudFoundryDeploy
#         uses: SAP/project-piper-action@master
#         with:
#           command: cloudFoundryDeploy


#       - name: mavenExecuteStaticCodeChecks
#         uses: SAP/project-piper-action@master
#         with:
#           command: mavenExecuteStaticCodeChecks
